name: flutter_klipper
description: Klipper/Moonraker client library for building Dart/Flutter apps for 3D printers
version: 0.0.1
repository: https://github.com/Alexandre2006/flutter_klipper
homepage: https://github.com/Alexandre2006/flutter_klipper
issue_tracker: https://github.com/Alexandre2006/flutter_klipper/issues
documentation: https://github.com/Alexandre2006/flutter_klipper

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  json_rpc_2: ^3.0.2
  state_notifier: ^0.7.2+1
  web_socket_channel: ^2.3.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
